### PR TITLE
Removed future and type-casted RADIUS_PORT

### PR DESCRIPTION
**Pull request by hwehr**
Hello,
I had exceptions, when I tried to run django-radius on Python 3.10. This was because of the old version of the future package.
I removed the future references completely because I think, the future packet should be imported in the main project if needed and not by a package.

Then I further type-casted RADIUS_PORT explicitely to int because if you are using env-variables in settings.py, there are no types in the enviroment; and then pyrad is not starting roperly with a port as string-type.

### CODE REVIEW

**Comment by AlanCoding** [comment]
I had originally opened https://github.com/robgolding/django-radius/issues/15 and pretty soon after we hit issues due to an outdated `future` library as well. I looked through the module, and I don't see anything specific to python 3, and I believe this fix should work much better.

**Comment by john-westcott-iv** [comment]
These changes would be very helpful!

**Review by john-westcott-iv — APPROVED** [review]

**Comment by AlanCoding** [comment]
If you see this @robgolding, we advocate to merge this.

**Comment by robgolding** [comment]
Thanks all, merging!

**Pull request merged**
